[package]
name = "lords"
version = "1.0.0"

# Build each contract as a standalone JSON file
[[target.starknet-contract]]

[scripts]
fmt = "cairo-format --recursive src/l2"
check_fmt = "cairo-format --recursive --check --print-parsing-errors src/l2"
